# Generated by Django 5.2.8 on 2026-04-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('app', 'APP'), ('tagline', 'Brand Statement / Company Profile Intro'), ('alamat', 'Contact'), ('visi', 'Visi Misi'), ('brandcontent', 'Brand Content'), ('program', 'Programs'), ('faq', 'Frequently Asked Questions')], max_length=100)),
                ('judul', models.CharField(max_length=200)),
                ('keterangan', models.TextField()),
                ('judulE', models.CharField(max_length=200)),
                ('keteranganE', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='informasi/%Y/%m/')),
            ],
        ),
        migrations.DeleteModel(
            name='PotensiBaru',
        ),
        migrations.DeleteModel(
            name='PotensiEkonomi',
        ),
        migrations.DeleteModel(
            name='SimtaxSession',
        ),
        migrations.DeleteModel(
            name='TargetPajak',
        ),
        migrations.DeleteModel(
            name='TransaksiPajak',
        ),
    ]
