# Generated by Django 5.2.8 on 2026-04-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_informasi_delete_potensibaru_delete_potensiekonomi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informasi',
            name='judulE',
        ),
        migrations.RemoveField(
            model_name='informasi',
            name='keteranganE',
        ),
    ]
