# Generated by Django 5.2.8 on 2026-04-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_informasi_judule_remove_informasi_keterangane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informasi',
            name='kategori',
            field=models.CharField(choices=[('app', 'APP'), ('tagline', 'Brand Statement / Company Profile Intro'), ('alamat', 'Contact'), ('visi', 'Visi Misi'), ('brandcontent', 'Brand Content'), ('program', 'Programs'), ('faq', 'Frequently Asked Questions'), ('lead', 'leadership')], max_length=100),
        ),
    ]
