# Generated by Django 5.2.8 on 2026-04-18 00:30

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_informasi_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='informasi',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_to),
        ),
        migrations.AlterField(
            model_name='informasi',
            name='kategori',
            field=models.CharField(choices=[('app', 'APP'), ('tagline', 'Brand Statement / Company Profile Intro'), ('alamat', 'Contact'), ('visi', 'Visi Misi'), ('brandcontent', 'Brand Content'), ('program', 'Programs'), ('faq', 'Frequently Asked Questions'), ('lead', 'Leadership'), ('pendaftaran', 'Enrollment'), ('medsos', 'Media Sosial')], max_length=100),
        ),
    ]
